// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Empty: typeof import('./components/empty/empty.vue')['default']
    Loading: typeof import('./components/loading/loading.vue')['default']
    LoginPopup: typeof import('./views/login/components/login-popup.vue')['LoginPopup']
    Message: typeof import('./components/message/message.vue')['default']
    NavBar: typeof import('./views/chat/components/nav-bar/nav-bar.vue')['NavBar']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
